version: '3.3'
services:
  db:
    container_name: postgres
    image: postgres:10.5-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
    - 5432:5432
    volumes:
    - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata